version: '3'
services:
  patient-service:
    build: ./patient-service # Chemin vers le répertoire contenant le Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootroot