version: '3.8'

services:
  mysql-patient:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=patient
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  patient-service:
    depends_on:
      - mysql-patient
    image: patient-service
    environment:
      - MYSQL_URL=mysql-patient:3306
      - MYSQL_DATABASE=patient
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootroot
    ports:
      - 8081:8081

        # il faut preciser que le micro-service depend de la base de donnees mysql-patient



volumes:
  mysql-data: